//
// Created by sy200 on 24-12-17.
//

#ifndef RAILWAYSYSTEM_ERROR_H
#define RAILWAYSYSTEM_ERROR_H

enum error{
    SUCCESS=0,
    DB_ALREADY_OPENED=101,
    DB_ALREADY_CLOSED=111,
    CONFIG_FILE_BROKEN=201,
    NO_SUCH_RECORD=301,
    TOO_MANY_RECORDS=302,
    UNKNOWN_SQLITE_ERR=399
};

#endif //RAILWAYSYSTEM_ERROR_H
